import os
import random
from glob import glob

import torch
from framework import TensorSpec
from framework.datatypes import to_torch_dtype
from framework.devices import torch_device_map
from scipy.io import mmread


def _output_dir():
    return os.environ.get("INFINICORE_SPARSE_MTX_DIR")


def _fmt_density(density):
    return f"{density:.6g}".replace(".", "p")


def density_nnz(total, density):
    if total <= 0:
        raise ValueError("total element count must be positive")
    nnz = int(total * density + 0.5)
    return min(total, max(1, nnz))


def random_csr_indices(rows, cols, density, *, seed):
    total = rows * cols
    nnz = density_nnz(total, density)
    rng = random.Random(seed)
    positions = sorted(rng.sample(range(total), nnz))
    crow = [0] * (rows + 1)
    col = []
    for position in positions:
        row = position // cols
        crow[row + 1] += 1
        col.append(position % cols)
    for row in range(rows):
        crow[row + 1] += crow[row]
    return crow, col


def random_spvec_indices(size, density, *, seed):
    nnz = density_nnz(size, density)
    rng = random.Random(seed)
    return sorted(rng.sample(range(size), nnz))


def _require_output_dir():
    out_dir = _output_dir()
    if not out_dir:
        raise RuntimeError(
            "Set INFINICORE_SPARSE_MTX_DIR to the directory containing mtx files "
            "generated by the non-bench sparse tests."
        )
    return out_dir


def _find_one(pattern):
    matches = sorted(glob(pattern))
    if not matches:
        raise FileNotFoundError(f"No mtx file matches: {pattern}")
    if len(matches) > 1:
        raise RuntimeError(f"Multiple mtx files match {pattern}: {matches}")
    return matches[0]


def _read_coordinate_mtx(path):
    matrix = mmread(path)
    if hasattr(matrix, "tocoo"):
        coo = matrix.tocoo()
        rows, cols = coo.shape
        return rows, cols, list(zip(coo.row.tolist(), coo.col.tolist(), coo.data.tolist()))

    rows, cols = matrix.shape
    coo = matrix.nonzero()
    entries = [
        (int(row), int(col), float(matrix[row, col]))
        for row, col in zip(coo[0].tolist(), coo[1].tolist())
    ]
    return rows, cols, entries


def load_csr(name, rows, cols, *, density):
    out_dir = _require_output_dir()
    pattern = os.path.join(
        out_dir,
        f"{name}_rows{rows}_cols{cols}_nnz*_density{_fmt_density(density)}.mtx",
    )
    path = _find_one(pattern)
    file_rows, file_cols, entries = _read_coordinate_mtx(path)
    if file_rows != rows or file_cols != cols:
        raise ValueError(
            f"Shape mismatch in {path}: expected ({rows}, {cols}), "
            f"got ({file_rows}, {file_cols})"
        )

    entries.sort()
    crow = [0] * (rows + 1)
    col = []
    values = []
    for row, col_idx, value in entries:
        if row < 0 or row >= rows or col_idx < 0 or col_idx >= cols:
            raise ValueError(f"Out-of-range entry in {path}: ({row}, {col_idx})")
        crow[row + 1] += 1
        col.append(col_idx)
        values.append(value)
    for row in range(rows):
        crow[row + 1] += crow[row]
    return crow, col, values


def load_spvec(name, size, *, density):
    out_dir = _require_output_dir()
    pattern = os.path.join(
        out_dir,
        f"{name}_size{size}_nnz*_density{_fmt_density(density)}.mtx",
    )
    path = _find_one(pattern)
    rows, cols, entries = _read_coordinate_mtx(path)
    if rows != size or cols != 1:
        raise ValueError(f"Shape mismatch in {path}: expected ({size}, 1), got ({rows}, {cols})")

    indices = []
    values = []
    for row, col, value in entries:
        if col != 0 or row < 0 or row >= size:
            raise ValueError(f"Out-of-range vector entry in {path}: ({row}, {col})")
        indices.append(row)
        values.append(value)
    pairs = sorted(zip(indices, values), key=lambda item: item[0])
    return [index for index, _ in pairs], [value for _, value in pairs]


class ValuesFromListSpec(TensorSpec):
    def __init__(self, values, *, dtype, name="values"):
        super().__init__(shape=(len(values),), dtype=dtype, name=name)
        self.values = list(values)

    def create_torch_tensor(self, device):
        return torch.tensor(
            self.values,
            dtype=to_torch_dtype(self.dtype),
            device=torch_device_map[device],
        )


def _write_header(f, rows, cols, nnz, *, name, density):
    f.write("%%MatrixMarket matrix coordinate real general\n")
    f.write(f"% name: {name}\n")
    if density is not None:
        f.write(f"% density: {density:.12g}\n")
    f.write(f"{rows} {cols} {nnz}\n")


_WRITE_BATCH_LINES = 65536


def _values_for_write(values, nnz):
    if values is None:
        return None
    if hasattr(values, "detach"):
        values = values.detach().cpu().reshape(-1).tolist()
    if len(values) < nnz:
        raise ValueError(f"Expected at least {nnz} sparse values, got {len(values)}")
    return values


def maybe_write_csr(name, rows, cols, crow, col, *, values=None, density=None):
    out_dir = _output_dir()
    if not out_dir:
        return
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(
        out_dir,
        f"{name}_rows{rows}_cols{cols}_nnz{len(col)}_density{_fmt_density(density or 0)}.mtx",
    )
    values = _values_for_write(values, len(col))
    with open(path, "w", encoding="utf-8") as f:
        _write_header(f, rows, cols, len(col), name=name, density=density)
        lines = []
        for row in range(rows):
            row_index = row + 1
            for ptr in range(crow[row], crow[row + 1]):
                value = 1.0 if values is None else float(values[ptr])
                lines.append(f"{row_index} {col[ptr] + 1} {value:.9g}\n")
                if len(lines) >= _WRITE_BATCH_LINES:
                    f.writelines(lines)
                    lines.clear()
        if lines:
            f.writelines(lines)


def maybe_write_spvec(name, size, indices, *, values=None, density=None):
    out_dir = _output_dir()
    if not out_dir:
        return
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(
        out_dir,
        f"{name}_size{size}_nnz{len(indices)}_density{_fmt_density(density or 0)}.mtx",
    )
    values = _values_for_write(values, len(indices))
    with open(path, "w", encoding="utf-8") as f:
        _write_header(f, size, 1, len(indices), name=name, density=density)
        lines = []
        for ptr, index in enumerate(indices):
            value = 1.0 if values is None else float(values[ptr])
            lines.append(f"{index + 1} 1 {value:.9g}\n")
            if len(lines) >= _WRITE_BATCH_LINES:
                f.writelines(lines)
                lines.clear()
        if lines:
            f.writelines(lines)
