import os
from glob import glob


def _output_dir():
    return os.environ.get("INFINICORE_SPARSE_MTX_DIR")


def _fmt_density(density):
    return f"{density:.6g}".replace(".", "p")


def _require_output_dir():
    out_dir = _output_dir()
    if not out_dir:
        raise RuntimeError(
            "Set INFINICORE_SPARSE_MTX_DIR to the directory containing mtx files "
            "generated by the non-bench sparse tests."
        )
    return out_dir


def _find_one(pattern):
    matches = sorted(glob(pattern))
    if not matches:
        raise FileNotFoundError(f"No mtx file matches: {pattern}")
    if len(matches) > 1:
        raise RuntimeError(f"Multiple mtx files match {pattern}: {matches}")
    return matches[0]


def _read_coordinate_mtx(path):
    with open(path, "r", encoding="utf-8") as f:
        header = f.readline().strip()
        if not header.startswith("%%MatrixMarket matrix coordinate"):
            raise ValueError(f"Unsupported MatrixMarket file: {path}")

        line = f.readline()
        while line and line.startswith("%"):
            line = f.readline()
        if not line:
            raise ValueError(f"Missing MatrixMarket size line: {path}")

        rows, cols, nnz = (int(v) for v in line.split())
        entries = []
        for line in f:
            if not line.strip() or line.startswith("%"):
                continue
            row, col, *_ = line.split()
            entries.append((int(row) - 1, int(col) - 1))

    if len(entries) != nnz:
        raise ValueError(f"Expected {nnz} entries in {path}, got {len(entries)}")
    return rows, cols, entries


def load_csr(name, rows, cols, *, density):
    out_dir = _require_output_dir()
    pattern = os.path.join(
        out_dir,
        f"{name}_rows{rows}_cols{cols}_nnz*_density{_fmt_density(density)}.mtx",
    )
    path = _find_one(pattern)
    file_rows, file_cols, entries = _read_coordinate_mtx(path)
    if file_rows != rows or file_cols != cols:
        raise ValueError(
            f"Shape mismatch in {path}: expected ({rows}, {cols}), "
            f"got ({file_rows}, {file_cols})"
        )

    entries.sort()
    crow = [0] * (rows + 1)
    col = []
    for row, col_idx in entries:
        if row < 0 or row >= rows or col_idx < 0 or col_idx >= cols:
            raise ValueError(f"Out-of-range entry in {path}: ({row}, {col_idx})")
        crow[row + 1] += 1
        col.append(col_idx)
    for row in range(rows):
        crow[row + 1] += crow[row]
    return crow, col


def load_spvec(name, size, *, density):
    out_dir = _require_output_dir()
    pattern = os.path.join(
        out_dir,
        f"{name}_size{size}_nnz*_density{_fmt_density(density)}.mtx",
    )
    path = _find_one(pattern)
    rows, cols, entries = _read_coordinate_mtx(path)
    if rows != size or cols != 1:
        raise ValueError(f"Shape mismatch in {path}: expected ({size}, 1), got ({rows}, {cols})")

    indices = []
    for row, col in entries:
        if col != 0 or row < 0 or row >= size:
            raise ValueError(f"Out-of-range vector entry in {path}: ({row}, {col})")
        indices.append(row)
    return sorted(indices)


def _write_header(f, rows, cols, nnz, *, name, density):
    f.write("%%MatrixMarket matrix coordinate real general\n")
    f.write(f"% name: {name}\n")
    if density is not None:
        f.write(f"% density: {density:.12g}\n")
    f.write(f"{rows} {cols} {nnz}\n")


def maybe_write_csr(name, rows, cols, crow, col, *, density=None):
    out_dir = _output_dir()
    if not out_dir:
        return
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(
        out_dir,
        f"{name}_rows{rows}_cols{cols}_nnz{len(col)}_density{_fmt_density(density or 0)}.mtx",
    )
    with open(path, "w", encoding="utf-8") as f:
        _write_header(f, rows, cols, len(col), name=name, density=density)
        for row in range(rows):
            for ptr in range(crow[row], crow[row + 1]):
                f.write(f"{row + 1} {col[ptr] + 1} 1\n")


def maybe_write_spvec(name, size, indices, *, density=None):
    out_dir = _output_dir()
    if not out_dir:
        return
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(
        out_dir,
        f"{name}_size{size}_nnz{len(indices)}_density{_fmt_density(density or 0)}.mtx",
    )
    with open(path, "w", encoding="utf-8") as f:
        _write_header(f, size, 1, len(indices), name=name, density=density)
        for index in indices:
            f.write(f"{index + 1} 1 1\n")
