#ifdef ENABLE_METAX_MC_API
#define hpccDataType macaDataType
#define HPCC_R_32F MACA_R_32F
#define HPCC_R_64F MACA_R_64F
#define HPCC_R_16F MACA_R_16F
#define HPCC_R_16BF MACA_R_16BF
#define hpcc_bfloat162 maca_bfloat162
#define hpcc_bfloat16 maca_bfloat16
#define hcFloatComplex mcFloatComplex
#define hcDoubleComplex mcDoubleComplex
#define hcComplex mcComplex
#define hcSuccess mcSuccess
#define hcStreamWaitEvent mcStreamWaitEvent
#define hcStreamSynchronize mcStreamSynchronize
#define hcStreamEndCapture mcStreamEndCapture
#define hcStreamDestroy mcStreamDestroy
#define hcStreamCreate mcStreamCreate
#define hcStreamCaptureModeThreadLocal mcStreamCaptureModeThreadLocal
#define hcStreamCaptureModeRelaxed mcStreamCaptureModeRelaxed
#define hcStreamCaptureModeGlobal mcStreamCaptureModeGlobal
#define hcStreamCaptureMode mcStreamCaptureMode
#define hcStreamBeginCapture mcStreamBeginCapture
#define hcStream_t mcStream_t
#define hcSetDevice mcSetDevice
#define hcMemset mcMemset
#define hcMemsetAsync mcMemsetAsync
#define hcMemcpyKind mcMemcpyKind
#define hcMemcpyHostToHost mcMemcpyHostToHost
#define hcMemcpyHostToDevice mcMemcpyHostToDevice
#define hcMemcpyDeviceToHost mcMemcpyDeviceToHost
#define hcMemcpyDeviceToDevice mcMemcpyDeviceToDevice
#define hcMemcpyDefault mcMemcpyDefault
#define hcMemcpyAsync mcMemcpyAsync
#define hcMemcpy mcMemcpy
#define hcMemGetInfo mcMemGetInfo
#define hcMallocHost mcMallocHost
#define hcMallocAsync mcMallocAsync
#define hcMalloc mcMalloc
#define hcLaunchKernel mcLaunchKernel
#define hcGraphNode_t mcGraphNode_t
#define hcGraphLaunch mcGraphLaunch
#define hcGraphInstantiate mcGraphInstantiate
#define hcGraphExecDestroy mcGraphExecDestroy
#define hcGraphExec_t mcGraphExec_t
#define hcGraphDestroy mcGraphDestroy
#define hcGraph_t mcGraph_t
#define hcGetLastError mcGetLastError
#define hcGetDeviceProperties mcGetDeviceProperties
#define hcGetDeviceCount mcGetDeviceCount
#define hcGetDevice mcGetDevice
#define hcFreeHost mcFreeHost
#define hcFreeAsync mcFreeAsync
#define hcFree mcFree
#define hcEventSynchronize mcEventSynchronize
#define hcEventRecord mcEventRecord
#define hcEventQuery mcEventQuery
#define hcEventElapsedTime mcEventElapsedTime
#define hcEventDisableTiming mcEventDisableTiming
#define hcEventDestroy mcEventDestroy
#define hcEventDefault mcEventDefault
#define hcEventCreateWithFlags mcEventCreateWithFlags
#define hcEventCreate mcEventCreate
#define hcEventBlockingSync mcEventBlockingSync
#define hcEvent_t mcEvent_t
#define hcError_t mcError_t
#define hcdnnTensorFormat_t mcdnnTensorFormat_t
#define hcdnnTensorDescriptor_t mcdnnTensorDescriptor_t
#define hcdnnStatus_t mcdnnStatus_t
#define hcdnnSetTensor4dDescriptor mcdnnSetTensor4dDescriptor
#define hcdnnSetTensorNdDescriptor mcdnnSetTensorNdDescriptor
#define hcdnnSetStream mcdnnSetStream
#define hcdnnSetPooling2dDescriptor mcdnnSetPooling2dDescriptor
#define hcdnnSetPoolingNdDescriptor mcdnnSetPoolingNdDescriptor
#define hcdnnPoolingMode_t mcdnnPoolingMode_t
#define hcdnnPoolingForward mcdnnPoolingForward
#define hcdnnPoolingDescriptor_t mcdnnPoolingDescriptor_t
#define hcdnnHandle_t mcdnnHandle_t
#define hcdnnDestroyTensorDescriptor mcdnnDestroyTensorDescriptor
#define hcdnnDestroyPoolingDescriptor mcdnnDestroyPoolingDescriptor
#define hcdnnDestroyPoolingDescriptor mcdnnDestroyPoolingDescriptor
#define hcdnnDataType_t mcdnnDataType_t
#define hcdnnCreateTensorDescriptor mcdnnCreateTensorDescriptor
#define hcdnnCreateTensorDescriptor mcdnnCreateTensorDescriptor
#define hcdnnCreatePoolingDescriptor mcdnnCreatePoolingDescriptor
#define hcdnnCreate mcdnnCreate
#define HCDNN_TENSOR_NCHW MCDNN_TENSOR_NCHW
#define HCDNN_STATUS_SUCCESS MCDNN_STATUS_SUCCESS
#define HCDNN_STATUS_SUCCESS MCDNN_STATUS_SUCCESS
#define HCDNN_POOLING_AVERAGE_COUNT_INCLUDE_PADDING MCDNN_POOLING_AVERAGE_COUNT_INCLUDE_PADDING
#define HCDNN_NOT_PROPAGATE_NAN MCDNN_NOT_PROPAGATE_NAN
#define HCDNN_DATA_UINT8 MCDNN_DATA_UINT8
#define HCDNN_DATA_INT8 MCDNN_DATA_INT8
#define HCDNN_DATA_INT64 MCDNN_DATA_INT64
#define HCDNN_DATA_INT32 MCDNN_DATA_INT32
#define HCDNN_DATA_HALF MCDNN_DATA_HALF
#define HCDNN_DATA_HALF MCDNN_DATA_HALF
#define HCDNN_DATA_FLOAT MCDNN_DATA_FLOAT
#define HCDNN_DATA_FLOAT MCDNN_DATA_FLOAT
#define HCDNN_DATA_DOUBLE MCDNN_DATA_DOUBLE
#define HCDNN_DATA_BFLOAT16 MCDNN_DATA_BFLOAT16
#define hcDeviceSynchronize mcDeviceSynchronize
#define hcDeviceProp_t mcDeviceProp_t
#define hcDeviceGetAttribute mcDeviceGetAttribute
#define hcDeviceAttributeMultiProcessorCount mcDeviceAttributeMultiProcessorCount
#define hcclSum mcclSum
#define hcclSuccess mcclSuccess
#define hcclRedOp_t mcclRedOp_t
#define hcclProd mcclProd
#define hcclMin mcclMin
#define hcclMax mcclMax
#define hcclHalf mcclHalf
#define hcclFloat mcclFloat
#define hcclDataType_t mcclDataType_t
#define hcclCommInitAll mcclCommInitAll
#define hcclCommDestroy mcclCommDestroy
#define hcclComm_t mcclComm_t
#define hcclBfloat16 mcclBfloat16
#define hcclAvg mcclAvg
#define hcclAllReduce mcclAllReduce
#define hcblasSetStream mcblasSetStream
#define hcblasHandle_t mcblasHandle_t
#define hcblasGemmStridedBatchedEx mcblasGemmStridedBatchedEx
#define hcblasGemmEx mcblasGemmEx
#define hcblasCreate mcblasCreate
#define hcblasComputeType_t mcblasComputeType_t
#define hcblasSetPointerMode mcblasSetPointerMode
#define hcblasIsamax mcblasIsamax
#define hcblasIdamax mcblasIdamax
#define hcblasIsamin mcblasIsamin
#define hcblasIdamin mcblasIdamin
#define hcblasSasum mcblasSasum
#define hcblasDasum mcblasDasum
#define hcblasAxpyEx mcblasAxpyEx
#define hcblasScopy mcblasScopy
#define hcblasDcopy mcblasDcopy
#define hcblasDotEx mcblasDotEx
#define hcblasNrm2Ex mcblasNrm2Ex
#define hcblasRotEx mcblasRotEx
#define hcblasSrotg mcblasSrotg
#define hcblasDrotg mcblasDrotg
#define hcblasSrotm mcblasSrotm
#define hcblasDrotm mcblasDrotm
#define hcblasSrotmg mcblasSrotmg
#define hcblasDrotmg mcblasDrotmg
#define hcblasScalEx mcblasScalEx
#define hcblasSswap mcblasSswap
#define hcblasDswap mcblasDswap
#define hcblasSgbmv mcblasSgbmv
#define hcblasDgbmv mcblasDgbmv
#define hcblasSsbmv mcblasSsbmv
#define hcblasDsbmv mcblasDsbmv
#define hcblasSger mcblasSger
#define hcblasDger mcblasDger
#define hcblasSsyr mcblasSsyr
#define hcblasDsyr mcblasDsyr
#define hcblasSsyr2 mcblasSsyr2
#define hcblasDsyr2 mcblasDsyr2
#define hcblasSgemv mcblasSgemv
#define hcblasDgemv mcblasDgemv
#define hcblasSspmv mcblasSspmv
#define hcblasDspmv mcblasDspmv
#define hcblasSspr mcblasSspr
#define hcblasDspr mcblasDspr
#define hcblasSspr2 mcblasSspr2
#define hcblasDspr2 mcblasDspr2
#define hcblasSsymv mcblasSsymv
#define hcblasDsymv mcblasDsymv
#define hcblasChemv mcblasChemv
#define hcblasZhemv mcblasZhemv
#define hcblasCher mcblasCher
#define hcblasZher mcblasZher
#define hcblasStbmv mcblasStbmv
#define hcblasDtbmv mcblasDtbmv
#define hcblasStbsv mcblasStbsv
#define hcblasDtbsv mcblasDtbsv
#define hcblasStrmv mcblasStrmv
#define hcblasDtrmv mcblasDtrmv
#define hcblasStrsv mcblasStrsv
#define hcblasDtrsv mcblasDtrsv
#define HCBLAS_STATUS_SUCCESS MCBLAS_STATUS_SUCCESS
#define HCBLAS_OP_T MCBLAS_OP_T
#define HCBLAS_OP_N MCBLAS_OP_N
#define HCBLAS_FILL_MODE_UPPER MCBLAS_FILL_MODE_UPPER
#define HCBLAS_FILL_MODE_LOWER MCBLAS_FILL_MODE_LOWER
#define HCBLAS_DIAG_UNIT MCBLAS_DIAG_UNIT
#define HCBLAS_DIAG_NON_UNIT MCBLAS_DIAG_NON_UNIT
#define HCBLAS_GEMM_DEFAULT_TENSOR_OP MCBLAS_GEMM_DEFAULT_TENSOR_OP
#define HCBLAS_GEMM_DEFAULT MCBLAS_GEMM_DEFAULT
#define HCBLAS_COMPUTE_32F_FAST_TF32 MCBLAS_COMPUTE_32F_FAST_TF32
#define HCBLAS_COMPUTE_32F MCBLAS_COMPUTE_32F
#define HCBLAS_POINTER_MODE_DEVICE MCBLAS_POINTER_MODE_DEVICE
#define HCBLAS_POINTER_MODE_HOST MCBLAS_POINTER_MODE_HOST
#define __hpcc_fp8_e4m3 __maca_fp8_e4m3
#define __hpcc_bfloat16 __maca_bfloat16
#endif
